"""initial migration

Revision ID: 3e221fc82435
Revises: 
Create Date: 2024-01-21 17:05:22.735471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e221fc82435'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('submenus_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submenu',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('menu_id', sa.UUID(), nullable=True),
        sa.Column('dishes_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title', 'menu_id')
    )
    op.create_table('dish',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('submenu_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['submenu_id'], ['submenu.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title', 'submenu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('submenu')
    op.drop_table('menu')
    # ### end Alembic commands ###
