"""empty message

Revision ID: 7aafa387f4e6
Revises: 3e221fc82435
Create Date: 2024-01-21 17:08:52.859494

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '7aafa387f4e6'
down_revision: str | None = '3e221fc82435'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
